version: '3.4'
services:
  bff:
    image: oidcproxy-demo-bff:1.0
    container_name: bff
    ports:
      - 8443:8080
    networks:
      testnet:
        ipv4_address: 10.5.0.2
    environment:
      - RunLocallyWithDocker=true
      - OidcProxy__Auth0__ClientSecret={yourSecret}
      - OidcProxy__Auth0__ClientId={yourClientId}
      - OidcProxy__Auth0__Domain={yourDomain}
      - OidcProxy__Auth0__Audience={yourAudience}
      - OidcProxy__AlwaysRedirectToHttps=false
      - OidcProxy__CustomHostName=http://localhost:8443
      - ASPNETCORE_ENVIRONMENT=Development
      - OidcProxy__ReverseProxy__Clusters__spa__Destinations__spa__Address=http://host.docker.internal:4200
      - OidcProxy__ReverseProxy__Clusters__api__Destinations__api__Address=http://host.docker.internal:8080
  spa:
    image: oidcproxy-demo-spa:1.0
    container_name: spa
    ports:
      - "4200:80"
    networks:
      testnet:
        ipv4_address: 10.5.0.3
  api:
    image: oidcproxy-demo-api:1.0
    container_name: api
    ports:
      - 8080:8080
    networks:
      testnet:
        ipv4_address: 10.5.0.4
    environment:
      - OidcProxy__Auth0__Domain={yourDomain}
      - OidcProxy__Auth0__Audience={yourAudience}
networks:
  testnet:
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
